# Twitter OAuth Setting
twitter_key:    <%= ENV['TWITTER_KEY'] %>
twitter_secret: <%= ENV['TWITTER_SECRET'] %>

# Facebook OAuth Setting
facebook_app_id:     <%= ENV['545991468781881'] %>
facebook_app_secret: <%= ENV['d909894f72e9d95c14f3a66d445802ae'] %>

# GitHub OAuth Setting
github_client_id: <%= ENV['GITHUB_CLIENT_ID'] %>
github_secret:    <%= ENV['GITHUB_SECRET'] %>

# Gmail Pass
mail_password: <%= ENV['MAIL_PASSWORD'] %>
